version: '3'
services:
  nestjs:
    # image: 744db8e1f5cb
    build: .
    ports:
      - 3000:3000
    environment:
      - RUNNING_ENV=dev
    volumes:
      - ./:/app
    command: npm run start:dev
